### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ysangkok** [ewiger/jsmodem#2]
I know JsLinux is not FOSS. But you did not specify a license for your patches. I am considering if I could use some of it for networking support on jslm32, but if the license is restrictive I don't have to bother. Thanks in advance.

**Comment by ewiger** [comment]
I am very sorry for such a slow reaction. Yes, jsmodem patch is absolutely FOSS. I will add remarks accordingly.

**Comment by socketpair** [comment]
:)
I'm working on emscripten + qemu (!)

**Comment by ysangkok** [comment]
Closing since the license will be added as Ewiger said above. Thanks!
